const SET_ANSWER_QUEUE = "SET_ANSWER_QUEUE";
const SET_QUESTION_ANSWER = "SET_QUESTION_ANSWER";
const INCREASE_CURRENT_QUESTION = "INCREASE_CURRENT_QUESTION";
const RESET_REDUCER = "RESET_REDUCER";

export {
	SET_ANSWER_QUEUE,
	SET_QUESTION_ANSWER,
	INCREASE_CURRENT_QUESTION,
	RESET_REDUCER
}