const SELECT_FRAMEWORKS_STEP = "SELECT_FRAMEWORKS_STEP";
const SURVEY_STEP = "SURVEY_STEP";
const GIVE_COMMENT_STEP = "GIVE_COMMENT_STEP";
const SUBMISSION_STEP = "SUBMISSION_STEP";

export {
	SELECT_FRAMEWORKS_STEP,
	SURVEY_STEP,
	GIVE_COMMENT_STEP,
	SUBMISSION_STEP
}